#!/usr/bin/env ruby
# Check whether git repositories in home directory have been pushed to master.

def get_commit_hash(label)
  hash = `git rev-parse #{label} 2> /dev/null`
  if $?.to_i == 0
    hash
  else
    nil
  end
end

class Repo
  def initialize(repo_path)
    @path = repo_path
    Dir.chdir "#{repo_path}/.."

    @commit_head = get_commit_hash "HEAD"
    @commit_master = get_commit_hash "master"
    @commit_origin_master = get_commit_hash "origin/master"

    `git diff-files --quiet 2> /dev/null`
    @tree_dirty = $?.to_i != 0
    `git diff-index --cached HEAD --quiet 2> /dev/null`
    @index_dirty = $?.to_i != 0

    `git status 2> /dev/null`
    @broken = $?.to_i != 0
  end

  def has_origin?
    not @commit_origin_master.nil?
  end

  def has_master?
    not @commit_master.nil?
  end

  def latest_pushed?
    @commit_master == @commit_origin_master and has_master?
  end

  def dirty?
    @tree_dirty or @index_dirty
  end

  def broken?
    @broken
  end

  def path
    @path
  end
end

# -------

repo_paths = (`find ~ -name .git -type d`).split("\n")
repos = repo_paths.map do |path|
  print "."
  Repo.new path
end

def list_repo_category(text, repos, filter)
  repos_selected = repos.select &filter
  unless repos_selected.empty? then
    puts "\n#{text}"
    repos_selected.each do |r|
      puts "    #{r.path}"
    end
  end
end

list_repo_category "Repos without an origin:",                              repos, Proc.new { |r| not r.has_origin? }
list_repo_category "Repos with uncommitted changes:",                       repos, Proc.new { |r| r.dirty? }
list_repo_category "Repos out of sync with their origins:",                 repos, Proc.new { |r| r.has_origin? and not r.latest_pushed? }
list_repo_category "Repos without a master branch:",                        repos, Proc.new { |r| not r.has_master? }
list_repo_category "Repos that are just broken (git status doesn't work):", repos, Proc.new { |r| r.broken? }
